=== m2karthi/placementmangement/src/xml/recruiter/add_job.dtd
<!ELEMENT add_job (job_details,eligibility,salaryDetails,selectionProcess,additionalRequirements)>

<!ELEMENT job_details (designation,description)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT designation (#PCDATA)>

<!ELEMENT eligibility (10th_percentage,12th_percentage,cgpa,program)>
<!ELEMENT 10th_percentage (#PCDATA)>
<!ELEMENT 12th_percentage (#PCDATA)>
<!ELEMENT cgpa (#PCDATA)>
<!ELEMENT program (#PCDATA)>

<!ELEMENT salaryDetails (package,contactDetails)>
<!ELEMENT package (#PCDATA)>
<!ELEMENT contactDetails (#PCDATA)>

<!ELEMENT selectionProcess (aptitude_round,coding_round,technical_round,hr_round)>
<!ELEMENT aptitude_round (#PCDATA)>
<!ELEMENT coding_round (#PCDATA)>
<!ELEMENT technical_round (#PCDATA)>
<!ELEMENT hr_round (#PCDATA)>

<!ELEMENT additionalRequirements (courses,certificates)>
<!ELEMENT courses (#PCDATA)>
<!ELEMENT certificates (#PCDATA)>

=== m2karthi/placementmangement/src/xml/recruiter/add_job.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE add_job SYSTEM "add_job.dtd">
<add_job>
	<job_details>
		<designation>Software Developer</designation>
		<description>Work on various frameworks and tech stacks such as MEAN, MERN and other cross-platform frameworks like React Native and Flutter.</description>
	</job_details>
	
	<eligibility>
		<10th_percentage>95.2</10th_percentage>
		<12th_percentage>95.5</12th_percentage>
		<cgpa>9.5</cgpa>
		<program>CSE,ECE,EEE</program>
	</eligibility>
	
	<salaryDetails>
		<package>12 lpa</package>
		<contactDetails>phone: 9854678901</contactDetails>
	</salaryDetails>
	
	<selectionProcess>
		<aptitude_round>True</aptitude_round>
		<coding_round>True</coding_round>
		<technical_round>True</technical_round>
		<hr_round>False</hr_round>
	</selectionProcess>
	
	<additionalRequirements>
		<courses>Foundations of DSA, App developement fundamentals</courses>
		<certificates>AWS Cloud Practitioner, Cisco Networking Fundamentals</certificates>
	</additionalRequirements>

</add_job>
