=== m2karthi/placementmangement/src/xml/Student/student.dtd
<!ELEMENT student_info (basic_info,contact_info,education,grades,college_name)>


<!ELEMENT basic_info (firstName,lastName,id,dob,address,nationality,state,city>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT nationality (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT city (#PCDATA)>

<!ELEMENT contact_info (email,mobile,alternate_email,alternate_mobile)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT alternate_email (#PCDATA)>
<!ELEMENT alternate_mobile (#PCDATA)>

<!ELEMENT education (10th_marks,12th_marks,jee)>
<!ELEMENT 10th_marks (#PCDATA)>
<!ELEMENT 12th_marks (#PCDATA)>
<!ELEMENT jee (#PCDATA)>


<!ELEMENT grades (cgpa_at_2nd_sem,cgpa_at_4rth_sem,cgpa_at_6th_sem,cgpa_at_8th_sem>
<!ELEMENT cgpa_at_2nd_sem (#PCDATA)>
<!ELEMENT cgpa_at_4rth_sem (#PCDATA)>
<!ELEMENT cgpa_at_6th_sem (#PCDATA)>
<!ELEMENT cgpa_at_8th_sem (#PCDATA)>

<!ENTITY campusname "ASE Coimbatore">
<!ELEMENT campus_name (#PCDATA)>

=== m2karthi/placementmangement/src/xml/Student/studentdata.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE student SYSTEM "student.dtd">

<student_info>
<basic_info>
	<firstName>John Denver</firstName>
	<lastName>Daniels</lastName>
	<id>1024</id>
	<dob>08/06/2022</dob>
	<address>2/824 (30), Vela Avvenue, Tirupur</address>
	<nationality>Indian</nationality>
	<state>Tamilnadu</state>
	<city>Tirupur</city>
</basic_info>

<contact_info>
	<email>johnddenvar@gmail.com</email>
	<mobile>9876543210</mobile>
	<alternate_email>johnddenvar2@gmail.com</alternate_email>
	<alternate_mobile>985674536789</alternate_mobile>
</contact_info>

<education>	
	<10th_marks>460</10th_marks>
	<12th_marks>476</12th_marks>
	<jee>97.8</jee>
</education>

<grades>
	<cgpa_at_2nd_sem>9.1</cgpa_at_2nd_sem>
	<cgpa_at_4rth_sem>8.9</cgpa_at_4rth_sem>
	<cgpa_at_6th_sem>8.5</cgpa_at_6th_sem>
	<cgpa_at_8th_sem>8.7</cgpa_at_8th_sem>
</grades>

<campus_name>&campusname;</campus_name>

</student_info>
