=== m2karthi/placementmangement/src/xml/Admin/recruiter_details.dtd
<!ELEMENT recruit_details (company_name,opening_date,closing_date,job_designation,register_student,course,eligibility_cgpa,status)>

<!ELEMENT company_name (#PCDATA)>

<!ELEMENT opening_date (#PCDATA)>

<!ELEMENT closing_date (#PCDATA)>

<!ELEMENT job_designation (#PCDATA)>

<!ELEMENT register_student (#PCDATA)>

<!ELEMENT course (#PCDATA)>

<!ELEMENT eligibility_cgpa (#PCDATA)>

<!ELEMENT status (#PCDATA)>

=== m2karthi/placementmangement/src/xml/Admin/recruiter_details.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- <!DOCTYPE recruit_details SYSTEM "recruiter_details.dtd"> -->
<recruit_details
xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com recruiter_details.xsd">

	<company_name>Google</company_name>

	<opening_date>2022-12-20</opening_date>

	<closing_date>2022-12-25</closing_date>

	<job_designation>Software Developer</job_designation>

	<register_student>180</register_student>

	<course>B.Tech</course>

	<eligibility_cgpa>9.0</eligibility_cgpa>

	<status>Active</status>

</recruit_details>
